import type { Metadata } from "next";
import React from "react";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            padding: "1rem",
            backgroundColor: "black",
            color: "white",
            display: "flex",
            justifyContent: "space-between",
          }}
        >
          <Link href="/upload" style={{ color: "white", textDecoration: "none" }}>
            Cargar Imagen
          </Link>
          <Link href="/gallery" style={{ color: "white", textDecoration: "none" }}>
            Ver Galeria
          </Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}